idf_component_register(SRCS "main.cpp"
        "../lib/Status_LED/status_leds.cpp"
        "initializations.cpp"
        "../lib/Communication_Protocols/i2c_controller.cpp"
        "../lib/Communication_Protocols/i2c_peripheral.cpp"
        "../lib/Communication_Protocols/ESP_SPI.cpp"
        "../lib/ROS_stuff/ROS_Callbacks.cpp"
        "../lib/ROS_stuff/ROS_Publishers.cpp"
        "../lib/ROS_stuff/ROS_launch.cpp"
        "../lib/Robot/Robot.cpp"
        INCLUDE_DIRS "."
        "../include/Eigen"
        "../lib/Communication_Protocols"
        "../lib/Status_LED"
        "../lib/ROS_stuff"
        "../lib/Misc_Utils"
        "../lib/")